---
name: DateTime-Format-ISO8601
version: 0.06
author:
  - 'Joshua Hoblitt <jhoblitt@cpan.org>'
abstract: Parses ISO8601 formats
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  DateTime: 0.18
  DateTime::Format::Builder: 0.77
recommends:
  File::Find::Rule: 0.24
  Test::Distribution: 1.22
  Test::Pod: 0.95
provides:
  DateTime::Format::ISO8601:
    file: lib/DateTime/Format/ISO8601.pm
    version: 0.06
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
