--- #YAML:1.0
name: DateTime-Format-ISO8601
version: 0.03
license: perl
distribution_type: module
requires:
  DateTime: 0.13
  DateTime::Format::Builder: 0.75
recommends: {}
build_requires: {}
conflicts: {}
provides:
  DateTime::Format::ISO8601:
    file: lib/DateTime/Format/ISO8601.pm
    version: 0.03
generated_by: Module::Build version 0.18
